Repository StudentsAgainstCovid19/corona-aid, pull requests merged in 2020-06, with the labels that each got.

#7 Readme upgrade
  README.md
  SECURITY.md
Labels: documentation

#19 Next dev version
  src/assets/icons/blur_filter.svg
  src/assets/markers/example_pie_chart.svg
  src/assets/markers/intermed_prio.svg
  src/css/call_list_style.css
  src/css/clustered_list.css
  src/css/interaction_props.css
  src/css/popup_style.css
  src/example_xmls/call_list.xml
  src/example_xmls/detailed_infected.xml
  src/example_xmls/example_map_data.xml
  src/example_xmls/example_pie_chart.xml
  src/index.html
  src/js/CoronaOSM.js
  src/js/call_list.js
  src/js/clustered_list.js
  src/js/detailed_bar.js
  src/js/search_call_list.js
  src/xslt_scripts/xslt_calculate_prio.xsl
  src/xslt_scripts/xslt_call_list.xsl
  src/xslt_scripts/xslt_clustered_list.xsl
  src/xslt_scripts/xslt_detailed_view.xsl
  src/xslt_scripts/xslt_edit_symptoms.xsl
  src/xslt_scripts/xslt_pie_chart_gen.xsl
  src/xslt_scripts/xslt_prio_gpx.xsl
  src/xslt_scripts/xslt_priority_helpers.xsl
  src/xslt_scripts/xslt_show_illnesses.xsl
  src/xslt_scripts/xslt_string_helpers.xsl
Labels: enhancement, improvement

#20 Continuous release
  src/assets/icons/blur_filter.svg
  src/assets/markers/example_pie_chart.svg
  src/assets/markers/intermed_prio.svg
  src/css/call_list_style.css
  src/css/clustered_list.css
  src/css/interaction_props.css
  src/css/popup_style.css
  src/example_xmls/call_list.xml
  src/example_xmls/detailed_infected.xml
  src/example_xmls/example_map_data.xml
  src/example_xmls/example_pie_chart.xml
  src/index.html
  src/js/CoronaOSM.js
  src/js/call_list.js
  src/js/clustered_list.js
  src/js/detailed_bar.js
  src/js/search_call_list.js
  src/xslt_scripts/xslt_calculate_prio.xsl
  src/xslt_scripts/xslt_call_list.xsl
  src/xslt_scripts/xslt_clustered_list.xsl
  src/xslt_scripts/xslt_detailed_view.xsl
  src/xslt_scripts/xslt_edit_symptoms.xsl
  src/xslt_scripts/xslt_pie_chart_gen.xsl
  src/xslt_scripts/xslt_prio_gpx.xsl
  src/xslt_scripts/xslt_priority_helpers.xsl
  src/xslt_scripts/xslt_show_illnesses.xsl
  src/xslt_scripts/xslt_string_helpers.xsl
Labels: release

#24 Add first Corona Aid Logo to Readme
  README.md
Labels: documentation

#22 Add favicon
  src/favicon.ico
  src/index.html
Labels: enhancement

#26 Clustering improvements
  src/example_xmls/call_list.xml
  src/js/CoronaOSM.js
  src/js/call_list.js
  src/js/clustered_list.js
  src/js/detailed_bar.js
  src/js/shared_variables.js
  src/xslt_scripts/xslt_pie_chart_gen.xsl
  src/xslt_scripts/xslt_priority_helpers.xsl
  src/xslt_scripts/xslt_string_helpers.xsl
Labels: bug, documentation, enhancement, improvement

#27 Misc improvements
  src/example_xmls/call_list.xml
  src/js/call_list.js
  src/js/clustered_list.js
  src/js/detailed_bar.js
  src/js/index.js
  src/js/load_xslt.js
  src/js/search_call_list.js
  src/js/shared_variables.js
  src/xslt_scripts/xslt_calculate_prio.xsl
  src/xslt_scripts/xslt_detailed_view.xsl
Labels: enhancement, improvement

#28 Styling improvements
  .gitignore
  .idea/.gitignore
  .idea/corona-aid.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  src/assets/icons/list_button.svg
  src/assets/icons/list_button2.svg
  src/assets/icons/search_magnifier.svg
  src/assets/icons/wellbeing_slider.svg
  src/css/call_list_style.css
  src/css/detailed_view.css
  src/css/interaction_props.css
  src/index.html
  src/js/shared_variables.js
  src/js/slide_animations_listeners.js
  src/xslt_scripts/xslt_call_list.xsl
  src/xslt_scripts/xslt_detailed_view.xsl
  src/xslt_scripts/xslt_symptom_div.xsl
Labels: improvement

#29 Backend bindings
  src/css/call_list_style.css
  src/css/clustered_list.css
  src/css/detailed_view.css
  src/js/CoronaOSM.js
  src/js/call_list.js
  src/js/clustered_list.js
  src/js/detailed_bar.js
  src/js/index.js
  src/js/load_xslt.js
  src/js/search_call_list.js
  src/js/shared_variables.js
  src/js/slide_animations_listeners.js
  src/xslt_scripts/xslt_calculate_prio.xsl
  src/xslt_scripts/xslt_realtime_update.xsl
Labels: enhancement, improvement

#31 Checkbox styling
  src/assets/icons/check-circle.svg
  src/css/call_list_style.css
  src/css/detailed_view.css
  src/css/interaction_props.css
  src/xslt_scripts/xslt_detailed_view.xsl
  src/xslt_scripts/xslt_symptom_div.xsl
Labels: enhancement, improvement

#32 Add new scrollbar style
  src/css/call_list_style.css
  src/css/scrollbars.css
  src/index.html
Labels: improvement

#33 Rework detailed view functionality
  src/assets/icons/check-circle.svg
  src/assets/icons/close_button.svg
  src/assets/icons/last_button.svg
  src/assets/icons/next_button.svg
  src/assets/markers/high_prio.svg
  src/assets/markers/intermed_prio.svg
  src/assets/markers/lower_prio.svg
  src/assets/markers/tried_call.svg
  src/assets/markers/veryhigh_prio.svg
  src/css/call_list_style.css
  src/css/detailed_view.css
  src/css/interaction_props.css
  src/css/scrollbars.css
  src/index.html
  src/js/CoronaOSM.js
  src/js/detailed_bar.js
  src/js/index.js
  src/js/load_xslt.js
  src/js/search_call_list.js
  src/js/shared_variables.js
  src/js/slide_animations_listeners.js
  src/xslt_scripts/xslt_call_list.xsl
  src/xslt_scripts/xslt_detailed_view.xsl
  src/xslt_scripts/xslt_edit_symptoms.xsl
  src/xslt_scripts/xslt_merge_symptoms.xsl
  src/xslt_scripts/xslt_parse_symptoms.xsl
  src/xslt_scripts/xslt_show_illnesses.xsl
  src/xslt_scripts/xslt_symptom_div.xsl
Labels: enhancement, improvement

#30 Continuous release
  .gitignore
  .idea/.gitignore
  .idea/corona-aid.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  src/assets/icons/check-circle.svg
  src/assets/icons/close_button.svg
  src/assets/icons/last_button.svg
  src/assets/icons/list_button.svg
  src/assets/icons/list_button2.svg
  src/assets/icons/next_button.svg
  src/assets/icons/search_magnifier.svg
  src/assets/icons/wellbeing_slider.svg
  src/assets/markers/high_prio.svg
  src/assets/markers/intermed_prio.svg
  src/assets/markers/lower_prio.svg
  src/assets/markers/tried_call.svg
  src/assets/markers/veryhigh_prio.svg
  src/css/call_list_style.css
  src/css/clustered_list.css
  src/css/detailed_view.css
  src/css/interaction_props.css
  src/css/scrollbars.css
  src/index.html
  src/js/CoronaOSM.js
  src/js/call_list.js
  src/js/clustered_list.js
  src/js/detailed_bar.js
  src/js/index.js
  src/js/load_xslt.js
  src/js/search_call_list.js
  src/js/shared_variables.js
  src/js/slide_animations_listeners.js
  src/xslt_scripts/xslt_calculate_prio.xsl
  src/xslt_scripts/xslt_call_list.xsl
  src/xslt_scripts/xslt_detailed_view.xsl
  src/xslt_scripts/xslt_edit_symptoms.xsl
  src/xslt_scripts/xslt_merge_symptoms.xsl
  src/xslt_scripts/xslt_parse_symptoms.xsl
  src/xslt_scripts/xslt_realtime_update.xsl
  src/xslt_scripts/xslt_show_illnesses.xsl
  src/xslt_scripts/xslt_symptom_div.xsl
Labels: release

#34 Continue search functionality
  src/css/call_list_style.css
  src/css/interaction_props.css
  src/css/popup_style.css
  src/index.html
  src/js/call_list.js
  src/js/clustered_list.js
  src/js/detailed_bar.js
  src/js/search_call_list.js
  src/js/shared_variables.js
  src/js/slide_animations_listeners.js
  src/xslt_scripts/xslt_calculate_prio.xsl
  src/xslt_scripts/xslt_call_list.xsl
Labels: enhancement, improvement

#35 Prepare testdata
  src/index.html
  src/js/detailed_bar.js
  src/js/prepare_data.js
  src/js/search_call_list.js
  src/xslt_scripts/xslt_calculate_prio.xsl
  src/xslt_scripts/xslt_call_list.xsl
  src/xslt_scripts/xslt_detailed_view.xsl
Labels: enhancement, improvement

#36 Symptoms styling
  src/css/detailed_view.css
  src/css/interaction_props.css
  src/css/popup_style.css
  src/index.html
  src/xslt_scripts/xslt_edit_symptoms.xsl
  src/xslt_scripts/xslt_show_illnesses.xsl
Labels: improvement

#37 Minor improvements
  src/assets/icons/checkbox_not_set.svg
  src/css/detailed_view.css
  src/index.html
  src/xslt_scripts/xslt_call_list.xsl
  src/xslt_scripts/xslt_detailed_view.xsl
  src/xslt_scripts/xslt_pie_chart_gen.xsl
Labels: enhancement, improvement

#38 Realtime implementation
  src/index.html
  src/js/call_list.js
  src/js/detailed_bar.js
  src/js/index.js
  src/js/prepare_data.js
  src/js/search_call_list.js
  src/js/shared_variables.js
  src/xslt_scripts/xslt_call_list.xsl
  src/xslt_scripts/xslt_realtime_update.xsl
Labels: enhancement, improvement

#39 Bugfixes
  src/css/detailed_view.css
  src/js/call_list.js
  src/js/detailed_bar.js
  src/js/index.js
  src/js/search_call_list.js
  src/js/shared_variables.js
  src/xslt_scripts/xslt_call_list.xsl
  src/xslt_scripts/xslt_detailed_view.xsl
  src/xslt_scripts/xslt_notes_popup.xsl
  src/xslt_scripts/xslt_realtime_update.xsl
  src/xslt_scripts/xslt_symptom_div.xsl
Labels: enhancement, improvement

#40 Map improvements
  src/css/popup_style.css
  src/js/CoronaOSM.js
  src/js/call_list.js
  src/js/index.js
  src/js/load_xslt.js
  src/js/prepare_data.js
  src/js/search_call_list.js
  src/js/shared_variables.js
  src/xslt_scripts/xslt_edit_symptoms.xsl
  src/xslt_scripts/xslt_notes_popup.xsl
  src/xslt_scripts/xslt_prio_gpx.xsl
  src/xslt_scripts/xslt_show_illnesses.xsl
Labels: enhancement, improvement

#41 Alphatest improvements
  src/assets/icons/example_progressbar.svg
  src/css/call_list_style.css
  src/css/detailed_view.css
  src/css/interaction_props.css
  src/example_xmls/call_list.xml
  src/example_xmls/detailed_infected.xml
  src/example_xmls/example_config.xml
  src/example_xmls/example_map_data.xml
  src/example_xmls/example_pie_chart.xml
  src/example_xmls/preExIllnesses.xml
  src/index.html
  src/js/CoronaOSM.js
  src/js/action_bar.js
  src/js/call_list.js
  src/js/clustered_list.js
  src/js/detailed_bar.js
  src/js/index.js
  src/js/shared_variables.js
  src/js/slide_animations_listeners.js
  src/xslt_scripts/xslt_detailed_view.xsl
  src/xslt_scripts/xslt_progressbar.xsl
Labels: enhancement, improvement

#42 Continuous release
  README.md
  src/assets/icons/checkbox_not_set.svg
  src/assets/icons/example_progressbar.svg
  src/css/call_list_style.css
  src/css/detailed_view.css
  src/css/interaction_props.css
  src/css/popup_style.css
  src/example_xmls/call_list.xml
  src/example_xmls/detailed_infected.xml
  src/example_xmls/example_config.xml
  src/example_xmls/example_map_data.xml
  src/example_xmls/example_pie_chart.xml
  src/example_xmls/preExIllnesses.xml
  src/index.html
  src/js/CoronaOSM.js
  src/js/action_bar.js
  src/js/call_list.js
  src/js/clustered_list.js
  src/js/detailed_bar.js
  src/js/index.js
  src/js/load_xslt.js
  src/js/prepare_data.js
  src/js/search_call_list.js
  src/js/shared_variables.js
  src/js/slide_animations_listeners.js
  src/xslt_scripts/xslt_calculate_prio.xsl
  src/xslt_scripts/xslt_call_list.xsl
  src/xslt_scripts/xslt_detailed_view.xsl
  src/xslt_scripts/xslt_edit_symptoms.xsl
  src/xslt_scripts/xslt_notes_popup.xsl
  src/xslt_scripts/xslt_pie_chart_gen.xsl
  src/xslt_scripts/xslt_prio_gpx.xsl
  src/xslt_scripts/xslt_progressbar.xsl
  src/xslt_scripts/xslt_realtime_update.xsl
  src/xslt_scripts/xslt_show_illnesses.xsl
  src/xslt_scripts/xslt_symptom_div.xsl
Labels: release

#43 Codacy security improvements
  src/js/CoronaOSM.js
  src/js/clustered_list.js
  src/js/index.js
  src/js/load_xslt.js
  src/js/prepare_data.js
  src/js/search_call_list.js
Labels: improvement

#44 Fixed several errors that happened in last merge.
  src/js/CoronaOSM.js
  src/js/clustered_list.js
  src/js/shared_variables.js
  src/xslt_scripts/xslt_calculate_prio.xsl
  src/xslt_scripts/xslt_realtime_update.xsl
Labels: enhancement, improvement
