Repository StudentsAgainstCovid19/corona-aid, pull requests merged in 2020-07, with the labels that each got.

#45 Further alphatest improvements
  src/assets/example_districts.xml
  src/assets/icons/loading_animation.png
  src/css/interaction_props.css
  src/index.html
  src/js/CoronaOSM.js
  src/js/animations.js
  src/js/detailed_bar.js
  src/js/index.js
  src/js/prepare_data.js
  src/js/shared_variables.js
  src/xslt_scripts/xslt_detailed_view.xsl
  src/xslt_scripts/xslt_notes_popup.xsl
  src/xslt_scripts/xslt_progressbar.xsl
  src/xslt_scripts/xslt_show_districts.xsl
Labels: enhancement, improvement

#47 Xslt improvements
  src/js/detailed_bar.js
  src/js/load_xslt.js
  src/xslt_scripts/xslt_calculate_prio.xsl
  src/xslt_scripts/xslt_call_list.xsl
  src/xslt_scripts/xslt_clustered_list.xsl
  src/xslt_scripts/xslt_edit_symptoms.xsl
  src/xslt_scripts/xslt_merge_symptoms.xsl
  src/xslt_scripts/xslt_parse_symptoms.xsl
  src/xslt_scripts/xslt_pie_chart_gen.xsl
  src/xslt_scripts/xslt_realtime_update.xsl
  src/xslt_scripts/xslt_show_illnesses.xsl
  src/xslt_scripts/xslt_symptom_div.xsl
Labels: enhancement

#48 Styling improvement
  src/css/call_list_style.css
  src/css/detailed_view.css
  src/css/interaction_props.css
  src/css/popup_style.css
  src/index.html
  src/js/action_bar.js
  src/js/animations.js
  src/js/index.js
  src/xslt_scripts/xslt_progressbar.xsl
Labels: improvement

#46 Continuous release
  src/assets/Corona_Aid_Logo.jpg
  src/assets/example_districts.xml
  src/assets/icons/loading_animation.png
  src/css/call_list_style.css
  src/css/detailed_view.css
  src/css/interaction_props.css
  src/css/popup_style.css
  src/index.html
  src/js/CoronaOSM.js
  src/js/action_bar.js
  src/js/animations.js
  src/js/clustered_list.js
  src/js/detailed_bar.js
  src/js/index.js
  src/js/load_xslt.js
  src/js/prepare_data.js
  src/js/search_call_list.js
  src/js/shared_variables.js
  src/xslt_scripts/xslt_calculate_prio.xsl
  src/xslt_scripts/xslt_call_list.xsl
  src/xslt_scripts/xslt_clustered_list.xsl
  src/xslt_scripts/xslt_detailed_view.xsl
  src/xslt_scripts/xslt_edit_symptoms.xsl
  src/xslt_scripts/xslt_merge_symptoms.xsl
  src/xslt_scripts/xslt_notes_popup.xsl
  src/xslt_scripts/xslt_parse_symptoms.xsl
  src/xslt_scripts/xslt_pie_chart_gen.xsl
  src/xslt_scripts/xslt_progressbar.xsl
  src/xslt_scripts/xslt_realtime_update.xsl
  src/xslt_scripts/xslt_show_districts.xsl
  src/xslt_scripts/xslt_show_illnesses.xsl
  src/xslt_scripts/xslt_symptom_div.xsl
Labels: release

#55 Add a Codacy badge to README.md
  README.md
Labels: documentation

#50 Overall styling improvements
  src/css/call_list_style.css
  src/css/clustered_list.css
  src/css/detailed_view.css
  src/css/interaction_props.css
  src/index.html
Labels: improvement

#59 Bug fixes
  src/css/clustered_list.css
  src/css/interaction_props.css
  src/css/popup_style.css
  src/index.html
  src/js/CoronaOSM.js
  src/js/animations.js
  src/js/call_list.js
  src/js/clustered_list.js
  src/js/detailed_bar.js
  src/js/index.js
  src/js/load_xslt.js
  src/js/popup_handlers.js
  src/js/realtime_handler.js
  src/js/timeouts.js
Labels: enhancement, improvement

#61 Add alt attributes
  src/index.html
  src/xslt_scripts/xslt_clustered_list.xsl
Labels: improvement

#63 Codacy improvements & general code style improvements
  Dockerfile
  src/css/call_list_style.css
  src/css/detailed_view.css
  src/css/interaction_props.css
  src/css/popup_style.css
  src/js/CoronaOSM.js
  src/js/action_bar.js
  src/js/animations.js
  src/js/call_list.js
  src/js/clustered_list.js
  src/js/detailed_bar.js
  src/js/index.js
  src/js/load_xslt.js
  src/js/popup_handlers.js
  src/js/prepare_data.js
  src/js/realtime_handler.js
  src/js/search_call_list.js
  src/js/shared_variables.js
  src/js/timeouts.js
  src/xslt_scripts/xslt_call_list.xsl
Labels: improvement

#65 Feature/districts
  src/assets/Corona_Aid_Logo.jpg
  src/assets/Corona_Aid_Logo.png
  src/index.html
  src/js/CoronaOSM.js
  src/js/shared_variables.js
  src/xslt_scripts/xslt_show_districts.xsl
Labels: enhancement

#67 Improved code style.
  src/js/CoronaOSM.js
  src/js/detailed_bar.js
Labels: improvement

#68 Districts enhancements
  src/assets/example_districts.xml
  src/css/detailed_view.css
  src/css/popup_style.css
  src/index.html
  src/js/CoronaOSM.js
  src/js/detailed_bar.js
  src/js/shared_variables.js
  src/xslt_scripts/xslt_call_list.xsl
  src/xslt_scripts/xslt_edit_symptoms.xsl
  src/xslt_scripts/xslt_show_districts.xsl
  src/xslt_scripts/xslt_show_illnesses.xsl
Labels: enhancement

#62 Continuous release
  Dockerfile
  README.md
  src/assets/Corona_Aid_Logo.jpg
  src/assets/Corona_Aid_Logo.png
  src/assets/example_districts.xml
  src/css/call_list_style.css
  src/css/clustered_list.css
  src/css/detailed_view.css
  src/css/interaction_props.css
  src/css/popup_style.css
  src/index.html
  src/js/CoronaOSM.js
  src/js/action_bar.js
  src/js/animations.js
  src/js/call_list.js
  src/js/clustered_list.js
  src/js/detailed_bar.js
  src/js/index.js
  src/js/load_xslt.js
  src/js/prepare_data.js
  src/js/search_call_list.js
  src/js/shared_variables.js
  src/xslt_scripts/xslt_call_list.xsl
  src/xslt_scripts/xslt_clustered_list.xsl
  src/xslt_scripts/xslt_detailed_view.xsl
  src/xslt_scripts/xslt_edit_symptoms.xsl
  src/xslt_scripts/xslt_show_districts.xsl
  src/xslt_scripts/xslt_show_illnesses.xsl
Labels: release

#72 Help popup & design improvements
  src/assets/icons/help.svg
  src/assets/icons/reset_zoom.svg
  src/assets/icons/search_magnifier.svg
  src/css/call_list_style.css
  src/css/clustered_list.css
  src/css/detailed_view.css
  src/css/help_style.css
  src/css/interaction_props.css
  src/css/map_style.css
  src/css/popup_style.css
  src/help/colors.html
  src/help/help_popup.xml
  src/help/impressum.html
  src/help/navigation.html
  src/help/optimization.html
  src/help/piecharts.html
  src/help/priority.html
  src/index.html
  src/js/CoronaOSM.js
  src/js/action_bar.js
  src/js/clustered_list.js
  src/js/detailed_bar.js
  src/xslt_scripts/xslt_call_list.xsl
  src/xslt_scripts/xslt_clustered_list.xsl
  src/xslt_scripts/xslt_construct_help.xsl
Labels: enhancement, improvement

#60 Dtds to hell
  src/dtd/calculate_prio_result.dtd
  src/dtd/config.dtd
  src/dtd/construct_symptom_popup_xml_result.dtd
  src/dtd/create_pie_chart_result.dtd
  src/dtd/infected_compressed.dtd
  src/dtd/infected_id.dtd
  src/dtd/parse_symptoms_result.dtd
  src/dtd/push_history_item.dtd
  src/dtd/push_prescribe_test.dtd
  src/dtd/realtime_sse.dtd
  src/dtd/realtime_update_merged.dtd
  src/dtd/symptom.dtd
  src/js/CoronaOSM.js
  src/js/call_list.js
  src/js/detailed_bar.js
  src/js/load_xslt.js
  src/js/prepare_data.js
  src/runLocalServer.py
  src/xml_examples/calculate_prio_result_example.xml
  src/xml_examples/config_example.xml
  src/xml_examples/construct_symptom_popup_xml_result_example.xml
  src/xml_examples/create_pie_chart_result_example.xml
  src/xml_examples/infected_compressed_example.xml
  src/xml_examples/infected_id_example.xml
  src/xml_examples/parse_symptoms_result_example.xml
  src/xml_examples/push_history_item_example.dtd
  src/xml_examples/push_prescribe_test_example.xml
  src/xml_examples/realtime_sse_example.xml
  src/xml_examples/realtime_update_merged_example.xml
  src/xml_examples/symptoms_example.xml
  src/xslt_scripts/xslt_calculate_prio.xsl
  src/xslt_scripts/xslt_call_list.xsl
  src/xslt_scripts/xslt_clustered_list.xsl
  src/xslt_scripts/xslt_detailed_view.xsl
  src/xslt_scripts/xslt_edit_symptoms.xsl
  src/xslt_scripts/xslt_notes_popup.xsl
  src/xslt_scripts/xslt_parse_symptoms.xsl
  src/xslt_scripts/xslt_pie_chart_gen.xsl
  src/xslt_scripts/xslt_progressbar.xsl
  src/xslt_scripts/xslt_show_illnesses.xsl
  src/xslt_scripts/xslt_symptom_div.xsl
Labels: enhancement

#74 Revert "Dtds to hell"
  src/dtd/calculate_prio_result.dtd
  src/dtd/config.dtd
  src/dtd/construct_symptom_popup_xml_result.dtd
  src/dtd/create_pie_chart_result.dtd
  src/dtd/infected_compressed.dtd
  src/dtd/infected_id.dtd
  src/dtd/parse_symptoms_result.dtd
  src/dtd/push_history_item.dtd
  src/dtd/push_prescribe_test.dtd
  src/dtd/realtime_sse.dtd
  src/dtd/realtime_update_merged.dtd
  src/dtd/symptom.dtd
  src/js/CoronaOSM.js
  src/js/call_list.js
  src/js/detailed_bar.js
  src/js/load_xslt.js
  src/js/prepare_data.js
  src/runLocalServer.py
  src/xml_examples/calculate_prio_result_example.xml
  src/xml_examples/config_example.xml
  src/xml_examples/construct_symptom_popup_xml_result_example.xml
  src/xml_examples/create_pie_chart_result_example.xml
  src/xml_examples/infected_compressed_example.xml
  src/xml_examples/infected_id_example.xml
  src/xml_examples/parse_symptoms_result_example.xml
  src/xml_examples/push_history_item_example.dtd
  src/xml_examples/push_prescribe_test_example.xml
  src/xml_examples/realtime_sse_example.xml
  src/xml_examples/realtime_update_merged_example.xml
  src/xml_examples/symptoms_example.xml
  src/xslt_scripts/xslt_calculate_prio.xsl
  src/xslt_scripts/xslt_call_list.xsl
  src/xslt_scripts/xslt_clustered_list.xsl
  src/xslt_scripts/xslt_detailed_view.xsl
  src/xslt_scripts/xslt_edit_symptoms.xsl
  src/xslt_scripts/xslt_notes_popup.xsl
  src/xslt_scripts/xslt_parse_symptoms.xsl
  src/xslt_scripts/xslt_pie_chart_gen.xsl
  src/xslt_scripts/xslt_progressbar.xsl
  src/xslt_scripts/xslt_show_illnesses.xsl
  src/xslt_scripts/xslt_symptom_div.xsl
Labels: bug

#75 Continuous release to fix critical bug
  src/dtd/calculate_prio_result.dtd
  src/dtd/config.dtd
  src/dtd/construct_symptom_popup_xml_result.dtd
  src/dtd/create_pie_chart_result.dtd
  src/dtd/infected_compressed.dtd
  src/dtd/infected_id.dtd
  src/dtd/parse_symptoms_result.dtd
  src/dtd/push_history_item.dtd
  src/dtd/push_prescribe_test.dtd
  src/dtd/realtime_sse.dtd
  src/dtd/realtime_update_merged.dtd
  src/dtd/symptom.dtd
  src/js/CoronaOSM.js
  src/js/call_list.js
  src/js/detailed_bar.js
  src/js/load_xslt.js
  src/js/prepare_data.js
  src/runLocalServer.py
  src/xml_examples/calculate_prio_result_example.xml
  src/xml_examples/config_example.xml
  src/xml_examples/construct_symptom_popup_xml_result_example.xml
  src/xml_examples/create_pie_chart_result_example.xml
  src/xml_examples/infected_compressed_example.xml
  src/xml_examples/infected_id_example.xml
  src/xml_examples/parse_symptoms_result_example.xml
  src/xml_examples/push_history_item_example.dtd
  src/xml_examples/push_prescribe_test_example.xml
  src/xml_examples/realtime_sse_example.xml
  src/xml_examples/realtime_update_merged_example.xml
  src/xml_examples/symptoms_example.xml
  src/xslt_scripts/xslt_calculate_prio.xsl
  src/xslt_scripts/xslt_call_list.xsl
  src/xslt_scripts/xslt_clustered_list.xsl
  src/xslt_scripts/xslt_detailed_view.xsl
  src/xslt_scripts/xslt_edit_symptoms.xsl
  src/xslt_scripts/xslt_notes_popup.xsl
  src/xslt_scripts/xslt_parse_symptoms.xsl
  src/xslt_scripts/xslt_pie_chart_gen.xsl
  src/xslt_scripts/xslt_progressbar.xsl
  src/xslt_scripts/xslt_show_illnesses.xsl
  src/xslt_scripts/xslt_symptom_div.xsl
Labels: bug, release

#76 Bug fixes
  src/css/call_list_style.css
  src/css/clustered_list.css
  src/css/detailed_view.css
  src/css/help_style.css
  src/help/colors.html
  src/index.html
  src/xslt_scripts/xslt_clustered_list.xsl
  src/xslt_scripts/xslt_construct_help.xsl
  src/xslt_scripts/xslt_detailed_view.xsl
  src/xslt_scripts/xslt_edit_symptoms.xsl
  src/xslt_scripts/xslt_notes_popup.xsl
  src/xslt_scripts/xslt_show_illnesses.xsl
Labels: bug, improvement

#77 Add tooltip functionality
  src/assets/Corona_Aid_Logo.png
  src/css/call_list_style.css
  src/css/interaction_props.css
  src/css/map_style.css
  src/index.html
  src/js/tooltip_position.js
  src/xslt_scripts/xslt_call_list.xsl
Labels: enhancement

#78 Help pages
  src/help/colors.html
  src/help/navigation.html
  src/help/priority.html
  src/js/detailed_bar.js
  src/js/index.js
  src/xslt_scripts/xslt_construct_help.xsl
Labels: enhancement

#79 Dtds to hell
  src/dtd/calculate_prio_result.dtd
  src/dtd/config.dtd
  src/dtd/construct_symptom_popup_xml_result.dtd
  src/dtd/create_pie_chart_result.dtd
  src/dtd/infected_compressed.dtd
  src/dtd/infected_id.dtd
  src/dtd/parse_symptoms_result.dtd
  src/dtd/push_history_item.dtd
  src/dtd/push_prescribe_test.dtd
  src/dtd/realtime_sse.dtd
  src/dtd/realtime_update_merged.dtd
  src/dtd/symptom.dtd
  src/js/CoronaOSM.js
  src/js/call_list.js
  src/js/detailed_bar.js
  src/js/load_xslt.js
  src/js/prepare_data.js
  src/runLocalServer.py
  src/xml_examples/calculate_prio_result_example.xml
  src/xml_examples/config_example.xml
  src/xml_examples/construct_symptom_popup_xml_result_example.xml
  src/xml_examples/create_pie_chart_result_example.xml
  src/xml_examples/infected_compressed_example.xml
  src/xml_examples/infected_id_example.xml
  src/xml_examples/parse_symptoms_result_example.xml
  src/xml_examples/push_history_item_example.dtd
  src/xml_examples/push_prescribe_test_example.xml
  src/xml_examples/realtime_sse_example.xml
  src/xml_examples/realtime_update_merged_example.xml
  src/xml_examples/symptoms_example.xml
  src/xslt_scripts/xslt_calculate_prio.xsl
  src/xslt_scripts/xslt_call_list.xsl
  src/xslt_scripts/xslt_clustered_list.xsl
  src/xslt_scripts/xslt_detailed_view.xsl
  src/xslt_scripts/xslt_edit_symptoms.xsl
  src/xslt_scripts/xslt_notes_popup.xsl
  src/xslt_scripts/xslt_parse_symptoms.xsl
  src/xslt_scripts/xslt_pie_chart_gen.xsl
  src/xslt_scripts/xslt_progressbar.xsl
  src/xslt_scripts/xslt_show_illnesses.xsl
  src/xslt_scripts/xslt_symptom_div.xsl
Labels: enhancement

#80 Create LegalNotice.md
  LegalNotice.md
Labels: documentation

#81 tooltip fixes
  src/css/call_list_style.css
  src/js/tooltip_position.js
Labels: bug, improvement

#82 Adjust scaling of pie charts when zooming out
  src/js/CoronaOSM.js
Labels: improvement

#85 Splitted into more js files.
  src/index.html
  src/js/CoronaOSM.js
  src/js/action_bar.js
  src/js/backend_interaction.js
  src/js/detailed_bar.js
  src/js/index.js
  src/js/load_xslt.js
  src/js/piecharts.js
  src/js/popups.js
  src/js/search_call_list.js
  src/js/tooltip_position.js
Labels: improvement

#84 Fix/help menu improvements
  src/css/call_list_style.css
  src/css/help_style.css
  src/css/map_style.css
  src/help/help_popup.xml
  src/help/impressum.html
  src/index.html
  src/xslt_scripts/xslt_construct_help.xsl
Labels: enhancement, improvement

#88 Styling improvement
  src/assets/logo.png
  src/css/call_list_style.css
  src/css/clustered_list.css
  src/css/detailed_view.css
  src/css/help_style.css
  src/css/interaction_props.css
  src/css/map_style.css
  src/css/popup_style.css
  src/help/colors.html
  src/help/navigation.html
  src/help/optimization.html
  src/help/piecharts.html
  src/help/priority.html
  src/index.html
  src/js/CoronaOSM.js
  src/js/animations.js
  src/js/call_list.js
  src/js/clustered_list.js
  src/js/detailed_bar.js
  src/js/index.js
  src/js/popups.js
  src/js/search_call_list.js
  src/xslt_scripts/xslt_call_list.xsl
  src/xslt_scripts/xslt_clustered_list.xsl
  src/xslt_scripts/xslt_detailed_view.xsl
  src/xslt_scripts/xslt_edit_symptoms.xsl
  src/xslt_scripts/xslt_show_illnesses.xsl
  src/xslt_scripts/xslt_symptom_div.xsl
Labels: improvement

#89 Fix progress bar
  src/assets/icons/example_progressbar.svg
  src/css/interaction_props.css
  src/index.html
  src/xslt_scripts/xslt_progressbar.xsl
Labels: improvement

#93 button works now with disabled style
  src/css/detailed_view.css
  src/js/popups.js
  src/xslt_scripts/xslt_detailed_view.xsl
Labels: improvement

#92 Unlock infected on close page
  src/js/index.js
Labels: bug, improvement

#95 Validate all XML files
  src/assets/icons/help.svg
  src/assets/icons/reset_zoom.svg
  src/dtd/district.dtd
  src/dtd/district_analytics.dtd
  src/dtd/help_popup.dtd
  src/help/colors.html
  src/help/help_popup.xml
  src/help/navigation.html
  src/help/optimization.html
  src/help/piecharts.html
  src/help/priority.html
  src/index.html
  src/xml_examples/config_example.xml
  src/xml_examples/district_analytics_example.xml
  src/xml_examples/district_example.xml
  src/xml_examples/infected_compressed_example.xml
  src/xml_examples/infected_id_example.xml
  src/xml_examples/push_history_item_example.xml
  src/xml_examples/symptoms_example.xml
Labels: enhancement, improvement

#94 Continuous release
  src/assets/icons/blur_filter.svg
  src/assets/icons/check-circle.svg
  src/assets/icons/checkbox_not_set.svg
  src/assets/icons/close_button.svg
  src/assets/icons/exampleWellbeingHistory.svg
  src/assets/icons/example_progressbar.svg
  src/assets/icons/help.svg
  src/assets/icons/last_button.svg
  src/assets/icons/list_button.svg
  src/assets/icons/list_button2.svg
  src/assets/icons/next_button.svg
  src/assets/icons/reset_zoom.svg
  src/assets/icons/search_magnifier.svg
  src/assets/icons/wellbeing_slider.svg
  src/assets/markers/example_pie_chart.svg
  src/assets/markers/high_prio.svg
  src/assets/markers/intermed_prio.svg
  src/assets/markers/lower_prio.svg
  src/assets/markers/tried_call.svg
  src/assets/markers/veryhigh_prio.svg
  src/assets/wellbeing_indicators/wellbeing_bad.svg
  src/assets/wellbeing_indicators/wellbeing_good.svg
  src/assets/wellbeing_indicators/wellbeing_intermediate.svg
  src/assets/wellbeing_indicators/wellbeing_verybad.svg
  src/assets/wellbeing_indicators/wellbeing_verygood.svg
  src/css/detailed_view.css
  src/css/interaction_props.css
  src/dtd/district.dtd
  src/dtd/district_analytics.dtd
  src/dtd/help_popup.dtd
  src/help/colors.html
  src/help/help_popup.xml
  src/help/navigation.html
  src/help/optimization.html
  src/help/piecharts.html
  src/help/priority.html
  src/index.html
  src/js/index.js
  src/js/popups.js
  src/xml_examples/config_example.xml
  src/xml_examples/district_analytics_example.xml
  src/xml_examples/district_example.xml
  src/xml_examples/infected_compressed_example.xml
  src/xml_examples/infected_id_example.xml
  src/xml_examples/push_history_item_example.xml
  src/xml_examples/symptoms_example.xml
  src/xslt_scripts/xslt_detailed_view.xsl
  src/xslt_scripts/xslt_progressbar.xsl
Labels: release

#96 Update README.md
  README.md
Labels: documentation

#99 Final countdown
  src/css/popup_style.css
  src/js/call_list.js
  src/js/index.js
  src/xslt_scripts/xslt_calculate_prio.xsl
  src/xslt_scripts/xslt_detailed_view.xsl
Labels: enhancement

#98 Release to v1.0.0
  README.md
  src/css/popup_style.css
  src/dtd/district.dtd
  src/dtd/realtime_sse.dtd
  src/dtd/realtime_update_merged.dtd
  src/js/call_list.js
  src/js/clustered_list.js
  src/js/index.js
  src/js/piecharts.js
  src/js/popups.js
  src/js/prepare_data.js
  src/js/shared_variables.js
  src/xml_examples/calculate_prio_result_example.xml
  src/xml_examples/construct_symptom_popup_xml_result_example.xml
  src/xml_examples/create_pie_chart_result_example.xml
  src/xml_examples/parse_symptoms_result_example.xml
  src/xml_examples/push_history_item_example.xml
  src/xml_examples/push_prescribe_test_example.xml
  src/xml_examples/realtime_sse_example.xml
  src/xml_examples/realtime_update_merged_example.xml
  src/xslt_scripts/xslt_calculate_prio.xsl
  src/xslt_scripts/xslt_detailed_view.xsl
  src/xslt_scripts/xslt_realtime_update.xsl
Labels: release

#100 Header improvement
  src/css/detailed_view.css
  src/xslt_scripts/xslt_call_list.xsl
  src/xslt_scripts/xslt_detailed_view.xsl
Labels: improvement
